export const home = (req, res) => res.send("Home");
export const join = (req, res) => res.send("Join");
export const login = (req, res) => res.send("Login");
export const account = (req, res) => res.send("Account");
export const edit = (req, res) => res.send("Edit");
export const courses = (req, res) => res.send("Courses");
export const coursesNew = (req, res) => res.send("Courses New");
export const coursesMine = (req, res) => res.send("Courses Mine");
export const documentation = (req, res) => res.send("Documentation");
export const buy = (req, res) => res.send("Buy");
export const refund = (req, res) => res.send("Refund");
export const remove = (req, res) => res.send("Remove");
